### ISSUE TITLE
Is this library usable?

### ISSUE THREAD

**Issue by matkuki** [centurysys/nim_asyncmodbus#1]
Hi,

Is this library ready to be used?
I don't mean production ready, but somewhat usable?

Thanks

**Comment by centurysys** [comment]
Hello,

We have only our product XIO-110 on hand which does not implement Holding Registers, so some functions are not implemented yet.

XIO-110 is this product.
https://www.centurysys.co.jp/products/protocol/xio110.html

We have confirmed that it works up to the test described in src/nim_asyncmodbus.nim.

**Comment by matkuki** [comment]
Very good, thank you for the information 👍
